Wait for cert-manager webhook to become ready before deploying OPA
Otherwise you will get:
Error: release opa failed: Internal error occurred: failed calling webhook
"certificates.admission.certmanager.k8s.io": the server is currently unable
to handle the request

The OPA Helm chart includes a separate way of generating the TLS
cert however. Might want to go with that instead of using cert-manager.